CREATE TABLE subjects (
  subject_id int4,
  name varchar
);
INSERT INTO subjects(subject_id, name) VALUES (1, 'Алтайский край');
INSERT INTO subjects(subject_id, name) VALUES (3, 'Краснодарский край');
INSERT INTO subjects(subject_id, name) VALUES (4, 'Красноярский край');
INSERT INTO subjects(subject_id, name) VALUES (5, 'Приморский край');
INSERT INTO subjects(subject_id, name) VALUES (7, 'Ставропольский край');
INSERT INTO subjects(subject_id, name) VALUES (8, 'ОЭР Хабаровского края');
INSERT INTO subjects(subject_id, name) VALUES (10, 'Амурская область');
INSERT INTO subjects(subject_id, name) VALUES (11, 'Архангельская область');
INSERT INTO subjects(subject_id, name) VALUES (12, 'Астраханская область');
INSERT INTO subjects(subject_id, name) VALUES (14, 'Белгородская область');
INSERT INTO subjects(subject_id, name) VALUES (15, 'Брянская область');
INSERT INTO subjects(subject_id, name) VALUES (17, 'Владимирская область');
INSERT INTO subjects(subject_id, name) VALUES (18, 'Волгоградская область');
INSERT INTO subjects(subject_id, name) VALUES (19, 'Вологодская область');
INSERT INTO subjects(subject_id, name) VALUES (20, 'Воронежская область');
INSERT INTO subjects(subject_id, name) VALUES (22, 'Нижегородская область');
INSERT INTO subjects(subject_id, name) VALUES (24, 'Ивановская область');
INSERT INTO subjects(subject_id, name) VALUES (25, 'Иркутская область');
INSERT INTO subjects(subject_id, name) VALUES (26, 'Республика Ингушетия');
INSERT INTO subjects(subject_id, name) VALUES (27, 'Калининградская область');
INSERT INTO subjects(subject_id, name) VALUES (28, 'Тверская область');
INSERT INTO subjects(subject_id, name) VALUES (29, 'Калужская область');
INSERT INTO subjects(subject_id, name) VALUES (33, 'Кировская область');
INSERT INTO subjects(subject_id, name) VALUES (34, 'Костромская область');
INSERT INTO subjects(subject_id, name) VALUES (35, 'Республика Крым');
INSERT INTO subjects(subject_id, name) VALUES (38, 'Курская область');
INSERT INTO subjects(subject_id, name) VALUES (42, 'Липецкая область');
INSERT INTO subjects(subject_id, name) VALUES (46, 'Московская область');
INSERT INTO subjects(subject_id, name) VALUES (49, 'Новгородская область');
INSERT INTO subjects(subject_id, name) VALUES (52, 'Омская область');
INSERT INTO subjects(subject_id, name) VALUES (54, 'Орловская область');
INSERT INTO subjects(subject_id, name) VALUES (58, 'Псковская область');
INSERT INTO subjects(subject_id, name) VALUES (60, 'Ростовская область');
INSERT INTO subjects(subject_id, name) VALUES (61, 'Рязанская область');
INSERT INTO subjects(subject_id, name) VALUES (66, 'Смоленская область');
INSERT INTO subjects(subject_id, name) VALUES (68, 'Тамбовская область');
INSERT INTO subjects(subject_id, name) VALUES (70, 'Тульская область');
INSERT INTO subjects(subject_id, name) VALUES (71, 'Тюменская область');
INSERT INTO subjects(subject_id, name) VALUES (75, 'Челябинская область');
INSERT INTO subjects(subject_id, name) VALUES (78, 'Ярославская область');
INSERT INTO subjects(subject_id, name) VALUES (80, 'Республика Башкортостан');
INSERT INTO subjects(subject_id, name) VALUES (81, 'Республика Бурятия');
INSERT INTO subjects(subject_id, name) VALUES (82, 'Республика Дагестан');
INSERT INTO subjects(subject_id, name) VALUES (83, 'Кабардино-Балкарская Республика');
INSERT INTO subjects(subject_id, name) VALUES (85, 'Республика Калмыкия');
INSERT INTO subjects(subject_id, name) VALUES (87, 'Республика Коми');
INSERT INTO subjects(subject_id, name) VALUES (88, 'Республика Марий Эл');
INSERT INTO subjects(subject_id, name) VALUES (89, 'Республика Мордовия');
INSERT INTO subjects(subject_id, name) VALUES (90, 'Республика Северная Осетия-Алания');
INSERT INTO subjects(subject_id, name) VALUES (91, 'Карачаево-Черкесская Республика');
INSERT INTO subjects(subject_id, name) VALUES (92, 'Республика Татарстан (Татарстан)');
INSERT INTO subjects(subject_id, name) VALUES (94, 'Удмуртская Республика');
INSERT INTO subjects(subject_id, name) VALUES (96, 'Чеченская Республика');
INSERT INTO subjects(subject_id, name) VALUES (101, 'Центральный энергорайон Якутии');
